package com.alumni.mapping;
// Generated 9 avr. 2013 21:29:11 by Hibernate Tools 3.2.1.GA



/**
 * Competence generated by hbm2java
 */
public class Competence  implements java.io.Serializable {


     private int idcompetence;
     private Integer idexperience;
     private String libelle;

    public Competence() {
    }

	
    public Competence(int idcompetence) {
        this.idcompetence = idcompetence;
    }
    public Competence(int idcompetence, Integer idexperience, String libelle) {
       this.idcompetence = idcompetence;
       this.idexperience = idexperience;
       this.libelle = libelle;
    }
   
    public int getIdcompetence() {
        return this.idcompetence;
    }
    
    public void setIdcompetence(int idcompetence) {
        this.idcompetence = idcompetence;
    }
    public Integer getIdexperience() {
        return this.idexperience;
    }
    
    public void setIdexperience(Integer idexperience) {
        this.idexperience = idexperience;
    }
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }




}


