package com.alumni.mapping;



/**
 * Entreprise generated by hbm2java
 */
public class Entreprise  implements java.io.Serializable {


     private int identreprise;
     private String nomentreprise;
     private String adresse;

    public Entreprise() {
    }

	
    public Entreprise(int identreprise, String nomentreprise) {
        this.identreprise = identreprise;
        this.nomentreprise = nomentreprise;
    }
    public Entreprise(int identreprise, String nomentreprise, String adresse) {
       this.identreprise = identreprise;
       this.nomentreprise = nomentreprise;
       this.adresse = adresse;
    }
   
    public int getIdentreprise() {
        return this.identreprise;
    }
    
    public void setIdentreprise(int identreprise) {
        this.identreprise = identreprise;
    }
    public String getNomentreprise() {
        return this.nomentreprise;
    }
    
    public void setNomentreprise(String nomentreprise) {
        this.nomentreprise = nomentreprise;
    }
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }




}


