package com.alumni.mapping;



/**
 * Etudiantannee generated by hbm2java
 */
public class Etudiantannee  implements java.io.Serializable {


     private EtudiantanneeId id;

    public Etudiantannee() {
    }

    public Etudiantannee(EtudiantanneeId id) {
       this.id = id;
    }
   
    public EtudiantanneeId getId() {
        return this.id;
    }
    
    public void setId(EtudiantanneeId id) {
        this.id = id;
    }




}


