package com.alumni.mapping;



/**
 * EtudiantanneeId generated by hbm2java
 */
public class EtudiantanneeId  implements java.io.Serializable {


     private int idformation;
     private int idetudiant;

    public EtudiantanneeId() {
    }

    public EtudiantanneeId(int idformation, int idetudiant) {
       this.idformation = idformation;
       this.idetudiant = idetudiant;
    }
   
    public int getIdformation() {
        return this.idformation;
    }
    
    public void setIdformation(int idformation) {
        this.idformation = idformation;
    }
    public int getIdetudiant() {
        return this.idetudiant;
    }
    
    public void setIdetudiant(int idetudiant) {
        this.idetudiant = idetudiant;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EtudiantanneeId) ) return false;
		 EtudiantanneeId castOther = ( EtudiantanneeId ) other; 
         
		 return (this.getIdformation()==castOther.getIdformation())
 && (this.getIdetudiant()==castOther.getIdetudiant());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdformation();
         result = 37 * result + this.getIdetudiant();
         return result;
   }   


}


