package com.alumni.mapping;
// Generated 9 avr. 2013 21:29:11 by Hibernate Tools 3.2.1.GA



/**
 * Etudiantannee generated by hbm2java
 */
public class Etudiantannee  implements java.io.Serializable {


     private EtudiantanneeId id;

    public Etudiantannee() {
    }

    public Etudiantannee(EtudiantanneeId id) {
       this.id = id;
    }
   
    public EtudiantanneeId getId() {
        return this.id;
    }
    
    public void setId(EtudiantanneeId id) {
        this.id = id;
    }




}


