package com.alumni.mapping;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Etudiant generated by hbm2java
 */
public class Etudiant extends Personne implements java.io.Serializable {

    private int idetudiant;
    private String nom;
    private String prenom;
    private String mail;
    private String mdp;
    private String adresse;
    private String telephone;
    private Date datenaissance;
    private String photoprofil;
    private String cv;
    private String souhaiteemploi;
    private String validation;
    private Set<Anneedeformation> anneeformation = new HashSet<Anneedeformation>(0);

    public Etudiant() {
        super();
    }

    public Etudiant(int idetudiant, String nom, String prenom, String mail, String mdp) {
        super(nom, prenom, mail, mdp);
        this.idetudiant = idetudiant;
    }

    public Etudiant(String nom, String prenom, String mail, String mdp, String adresse, String telephone, Date datenaissance, String photoprofil, String cv, String souhaiteemploie, String validation) {
        super(nom, prenom, mail, mdp);
        this.adresse = adresse;
        this.telephone = telephone;
        this.datenaissance = datenaissance;
        this.photoprofil = photoprofil;
        this.cv = cv;
        this.souhaiteemploi = souhaiteemploie;
        this.validation = validation;
    }
    
    

    public Etudiant(int idetudiant, String nom, String prenom, String mail, String mdp, String adresse, String telephone, Date datenaissance, String photoprofil, String cv, String souhaiteemploie, String validation) {
        super(nom, prenom, mail, mdp);
        this.idetudiant = idetudiant;
        this.adresse = adresse;
        this.telephone = telephone;
        this.datenaissance = datenaissance;
        this.photoprofil = photoprofil;
        this.cv = cv;
        this.souhaiteemploi = souhaiteemploie;
        this.validation = validation;
    }
    
     public Etudiant(int idetudiant, String nom, String prenom, String mail, String mdp, String adresse, String telephone, Date datenaissance, String photoprofil, String cv, String souhaiteemploie, String validation, Set<Anneedeformation> anneeFormation) {
        super(nom, prenom, mail, mdp);
        this.idetudiant = idetudiant;
        this.adresse = adresse;
        this.telephone = telephone;
        this.datenaissance = datenaissance;
        this.photoprofil = photoprofil;
        this.cv = cv;
        this.souhaiteemploi = souhaiteemploie;
        this.validation = validation;
        this.anneeformation = anneeFormation;
    }   

    public int getIdetudiant() {
        return this.idetudiant;
    }

    public void setIdetudiant(int idetudiant) {
        this.idetudiant = idetudiant;
    }

    public String getNom() {
        return this.nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    public String getPrenom() {
        return this.prenom;
    }

    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    public String getMail() {
        return this.mail;
    }

    public void setMail(String mail) {
        this.mail = mail;
    }

    public String getMdp() {
        return this.mdp;
    }

    public void setMdp(String mdp) {
        this.mdp = mdp;
    }

    public String getAdresse() {
        return this.adresse;
    }

    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    public String getTelephone() {
        return this.telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    public Date getDatenaissance() {
        return this.datenaissance;
    }

    public void setDatenaissance(Date datenaissance) {
        this.datenaissance = datenaissance;
    }

    public String getPhotoprofil() {
        return this.photoprofil;
    }

    public void setPhotoprofil(String photoprofil) {
        this.photoprofil = photoprofil;
    }

    public String getCv() {
        return this.cv;
    }

    public void setCv(String cv) {
        this.cv = cv;
    }

    public String getSouhaiteemploi() {
        return this.souhaiteemploi;
    }

    public void setSouhaiteemploi(String souhaiteemploi) {
        this.souhaiteemploi = souhaiteemploi;
    }

    public String getValidation() {
        return this.validation;
    }

    public void setValidation(String validation) {
        this.validation = validation;
    }

    public Set<Anneedeformation> getAnneeformation() {
        return anneeformation;
    }

    public void setAnneeformation(Set<Anneedeformation> anneeFormation) {
        this.anneeformation = anneeFormation;
    }
    
    
}
