package com.alumni.mapping;



/**
 * Salaire generated by hbm2java
 */
public class Salaire  implements java.io.Serializable {


     private int idsalaire;
     private Integer idexperience;
     private Double valeur;
     private Integer annee;

    public Salaire() {
    }

	
    public Salaire(int idsalaire) {
        this.idsalaire = idsalaire;
    }
    public Salaire(int idsalaire, Integer idexperience, Double valeur, Integer annee) {
       this.idsalaire = idsalaire;
       this.idexperience = idexperience;
       this.valeur = valeur;
       this.annee = annee;
    }
   
    public int getIdsalaire() {
        return this.idsalaire;
    }
    
    public void setIdsalaire(int idsalaire) {
        this.idsalaire = idsalaire;
    }
    public Integer getIdexperience() {
        return this.idexperience;
    }
    
    public void setIdexperience(Integer idexperience) {
        this.idexperience = idexperience;
    }
    public Double getValeur() {
        return this.valeur;
    }
    
    public void setValeur(Double valeur) {
        this.valeur = valeur;
    }
    public Integer getAnnee() {
        return this.annee;
    }
    
    public void setAnnee(Integer annee) {
        this.annee = annee;
    }




}


